// src/routes/cv.svelte
<script context="module">
  export function preload() {
    return this.fetch(`appearances.json`)
      .then((r) => r.json())
      .then((talks) => {
        return { talks };
      });
  }
</script>

<script>
  import metadata from "../../content/data/metadata.json";
  import cvInfo from "../../content/data/cv.json";
  import { onMount } from "svelte";
  import { separateByAt } from "../utils";
  import splitbee from "@splitbee/web";

  import Layout from "../components/Layout.svelte";
  import CVSection from "../components/CVSection.svelte";
  import JobExperience from "../components/JobExperience.svelte";
  import Appearances from "../components/Appearances.svelte";

  let { jobExperiences, skills, my_tech, education } = cvInfo;
  export let talks;

  jobExperiences = jobExperiences.map((job) => {
    const [position, company] = separateByAt(job.title);
    return {
      position,
      company,
      ...job,
    };
  });

  function keyToTitle(key) {
    return key.replace(/_/g, " ");
  }

  let doPrint = () => {
    console.log("noop print");
  };

  onMount(() => {
    doPrint = () => {
      try {
        console.log("print called");
        window.print();
      } catch (err) {
        console.log(err);
      }
    };
  });
</script>

<Layout title="CV | {metadata.siteTitle}" variant="narrow">
  <section class="download-bar hidden-print">
    <p>
      Get my latest CV <span
        role="img"
        title="is on the right link"
        aria-label="is on the right link">👉</span
      >
    </p>
    <button
      class="hidden-print button button-outline"
      on:click={doPrint}
      on:click={() => {
        splitbee.track("download_cv");
      }}
    >
      Download My CV
    </button>
  </section>
  <hr />

  <CVSection title="my tech">
    <p>{my_tech.join(" , ")}</p>
  </CVSection>

  <hr />

  <CVSection title="skills">
    {#each Object.keys(skills) as skill}
      <h3 style="text-transform: capitalize; margin-bottom: .5rem;">
        {keyToTitle(skill)}
      </h3>
      <p style="margin-top: 0;">
        {skills[skill].join(" , ")}
      </p>
    {/each}
  </CVSection>

  <hr />

  <CVSection title="education">
    <p>{education.join(" , ")}</p>
  </CVSection>

  <hr />

  <CVSection title="professional experiences">
    <ul class="list-none job-list">
      {#each jobExperiences as job}
        <li>
          <JobExperience
            position={job.position}
            company={job.company}
            date={job.date}
          >
            {job.description}</JobExperience
          >
          <hr />
        </li>
      {/each}
    </ul>
  </CVSection>

  <CVSection title="appearances">
    <ul class="list-none">
      <li><Appearances level={3} {talks} /></li>
    </ul>
  </CVSection>
  <hr />

  <CVSection title="Community contributions and Open Source">
    <ul class="list-none">
      <li>
        <h3>
          Long time StackOverflow contributor <small
            style="white-space: nowrap;padding-left: 1rem;font-weight: normal"
            >with a reputation of: {metadata.stackoverflowReputation}</small
          >
        </h3>
      </li>
      <li>
        <h3>
          Plenty of OS projects I've contributed to in the past
          <small>including but not limited to</small>
        </h3>
        <ul class="list-inline">
          <li>XState,</li>
          <li>XState Visualizer,</li>
          <li>XState.tips,</li>
          <li>React native offline,,</li>
          <li>Automated accessibility tests,</li>
          <li>Paypal universal video player,</li>
          <li>React power-plug,</li>
          <li>Alveron (pre: React woodworm),</li>
          <li>Carbon,</li>
          <li>React Static,,</li>
          <li>Graphpack,</li>
          <li>React native card flip,</li>
          <li>PullRequest.ir,</li>
          <li>React SVG Spinner, Todometer,</li>
          <li>Awesome Talks,</li>
          <li>Ant Design,</li>
          <li>Unfetch,</li>
          <li>Mitt and many more</li>
        </ul>
      </li>
    </ul>
  </CVSection>
</Layout>

<style>
  @media print {
    @page {
      size: auto;
      margin: 0mm;
    }

    :global(a) {
      text-decoration: underline !important;
    }

    :global(.job-experience) {
      border: none !important;
      padding-left: 0 !important;
      padding-right: 0 !important;
    }
  }

  .download-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .job-list {
    list-style: none;
  }

  .job-list li:first-child {
    margin-top: 2rem;
  }

  .job-list hr {
    margin-top: 2rem;
    margin-bottom: 2rem;
  }
</style>

// pages/cv.tsx
import { NextPage } from "next";
import { Layout } from "../src/Layout";
import { getAllPosts } from "../src/posts";
import { Seo } from "../src/Seo";
import { Post } from "../src/types";
import cvInfo from "../content/cv.json";
import { Appearances } from "../src/Appearance";
import {
  Box,
  Button,
  Divider,
  Heading,
  Text,
  List,
  ListItem,
  Link,
  VStack,
} from "@chakra-ui/react";
import { useMemo } from "react";
import { useMetadata } from "../src/MetadataContext";

function separateByAt(str: string) {
  return str.split("@");
}

function keyToTitle(key: string) {
  return key.replace(/_/g, " ");
}

function prepareJobExperiences<T extends { title: string }>(
  experiences: T[]
): Array<T & { position: string; company: string }> {
  return experiences.map((job) => {
    const [position, company] = separateByAt(job.title);
    return {
      position,
      company,
      ...job,
    };
  });
}

const JobExperience: React.FC<{
  position: string;
  date: string;
  company: string;
}> = ({ position, date, company, children }) => (
  <Box as="section" display="flex" flexDirection="column" gridGap="3">
    <Heading as="h3" fontSize="l">
      <strong>
        {position} {company && `at ${company}`}
      </strong>
      <Box as="small" marginTop="1" display="block">
        {date}
      </Box>
    </Heading>
    {children}
    <Divider />
  </Box>
);

const CVSection: React.FC<{ title: string; textArray?: string[] }> = ({
  title,
  textArray = [],
  children,
}) => (
  <Box
    as="section"
    display="flex"
    flexDirection="column"
    gridGap="7"
    className="cv-section"
  >
    <Heading fontSize="2xl" style={{ textTransform: "capitalize" }}>
      <strong>{title}</strong>
    </Heading>
    {textArray.map((t, i) => (
      <Text key={i}>{t}</Text>
    ))}
    {children}
  </Box>
);

const CV: NextPage<{ posts: Post[] }> = ({ posts }) => {
  const { skills, my_technologies, education } = cvInfo;

  const jobExperiences = useMemo(
    () => prepareJobExperiences(cvInfo.jobExperiences),
    []
  );

  const { default: metadata } = useMetadata();

  return (
    <>
      <Seo />
      <Layout posts={posts}>
        <Box display="flex" flexDirection="column" gridGap="5">
          <Box>
            <Button
              color="white"
              bg="gray.900"
              _hover={{ bg: "gray.700" }}
              _focus={{ bg: "gray.700" }}
              onClick={() => {
                // TODO: use a MD to PDF service, have it as an API route and use it here
                try {
                  window.print();
                } catch (err) {}
                //   splitbee.track("download_cv");
              }}
            >
              Download My Latest CV
            </Button>
          </Box>

          <Divider />

          <CVSection title="my technologies">
            <Text>{my_technologies.join(" , ")}</Text>
          </CVSection>

          <Divider />

          <CVSection title="skills">
            <Box display="flex" flexDirection="column" gridGap="7">
              {Object.keys(skills).map((skill, i) => (
                <Box display="flex" flexDirection="column" gridGap="2" key={i}>
                  <Heading as="h3" textTransform="capitalize" fontSize="l">
                    <strong>{keyToTitle(skill)}</strong>
                  </Heading>
                  <Text style={{ marginTop: 0 }}>
                    {skills[skill].join(" , ")}
                  </Text>
                </Box>
              ))}
            </Box>
          </CVSection>

          <Divider />

          <CVSection title="education">
            <Box>
              {education.map((edu) => (
                <Text key={edu}>{edu}</Text>
              ))}
            </Box>
          </CVSection>

          <Divider />

          <CVSection title="professional experiences">
            <List
              listStyleType="none"
              paddingLeft="4"
              display="flex"
              flexDirection="column"
              gridGap="5"
            >
              {jobExperiences.map((job, i) => (
                <ListItem key={i}>
                  <JobExperience
                    position={job.position}
                    company={job.company}
                    date={job.date}
                  >
                    {job.description}
                  </JobExperience>
                </ListItem>
              ))}
            </List>
          </CVSection>

          <CVSection title="appearances">
            <Appearances level={3} />
          </CVSection>
          <Divider />

          <CVSection title="Community contributions and Open Source">
            <VStack alignItems="flex-start" fontSize="md">
              <Box>
                <Heading as="h3" fontSize="l">
                  Long time StackOverflow contributor{" "}
                  <small
                    style={{
                      whiteSpace: "nowrap",
                      paddingLeft: "1rem",
                      fontWeight: "normal",
                    }}
                  >
                    {/* TODO: Have it as a build script that's written to the disk */}
                    {/* with a reputation of: {metadata.stackoverflowReputation} */}
                  </small>
                </Heading>
              </Box>
              <Box>
                For <abbr title="Open Source Software">OSS</abbr> contributions,
                checkout my{" "}
                <Link
                  textDecoration="underline"
                  isExternal
                  href={metadata.social.github.link}
                  whiteSpace="nowrap"
                >
                  Github Profile
                </Link>
              </Box>
            </VStack>
          </CVSection>
        </Box>
      </Layout>
    </>
  );
};

export const getStaticProps = async () => {
  return {
    props: {
      posts: await getAllPosts(),
    },
  };
};

export default CV;
